# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindowAudio2.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QGroupBox,
    QHBoxLayout, QHeaderView, QLabel, QLayout,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QSplitter, QTableWidget, QTableWidgetItem,
    QToolBar, QVBoxLayout, QWidget)

class Ui_MainWindowAudio(object):
    def setupUi(self, MainWindowAudio):
        if not MainWindowAudio.objectName():
            MainWindowAudio.setObjectName(u"MainWindowAudio")
        MainWindowAudio.setEnabled(True)
        MainWindowAudio.resize(1280, 720)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindowAudio.sizePolicy().hasHeightForWidth())
        MainWindowAudio.setSizePolicy(sizePolicy)
        MainWindowAudio.setMinimumSize(QSize(1104, 576))
        font = QFont()
        font.setPointSize(18)
        MainWindowAudio.setFont(font)
        self.actionNewFile = QAction(MainWindowAudio)
        self.actionNewFile.setObjectName(u"actionNewFile")
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentNew))
        self.actionNewFile.setIcon(icon)
        self.actionNewFile.setMenuRole(QAction.MenuRole.NoRole)
        self.actionOpenFile = QAction(MainWindowAudio)
        self.actionOpenFile.setObjectName(u"actionOpenFile")
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentOpen))
        self.actionOpenFile.setIcon(icon1)
        self.actionOpenFile.setMenuRole(QAction.MenuRole.NoRole)
        self.actionSave = QAction(MainWindowAudio)
        self.actionSave.setObjectName(u"actionSave")
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSave))
        self.actionSave.setIcon(icon2)
        self.actionSave.setMenuRole(QAction.MenuRole.NoRole)
        self.actionHome = QAction(MainWindowAudio)
        self.actionHome.setObjectName(u"actionHome")
        icon3 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoHome))
        self.actionHome.setIcon(icon3)
        self.actionHome.setMenuRole(QAction.MenuRole.NoRole)
        self.actionHome.setIconVisibleInMenu(False)
        self.actionSerialPort = QAction(MainWindowAudio)
        self.actionSerialPort.setObjectName(u"actionSerialPort")
        icon4 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.SoftwareUpdateAvailable))
        self.actionSerialPort.setIcon(icon4)
        self.actionSerialPort.setMenuRole(QAction.MenuRole.NoRole)
        self.actionViewGrid = QAction(MainWindowAudio)
        self.actionViewGrid.setObjectName(u"actionViewGrid")
        icon5 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.Computer))
        self.actionViewGrid.setIcon(icon5)
        self.actionViewGrid.setMenuRole(QAction.MenuRole.NoRole)
        self.actionSamplingSettings = QAction(MainWindowAudio)
        self.actionSamplingSettings.setObjectName(u"actionSamplingSettings")
        icon6 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentPageSetup))
        self.actionSamplingSettings.setIcon(icon6)
        self.actionSamplingSettings.setMenuRole(QAction.MenuRole.NoRole)
        self.actionSVM = QAction(MainWindowAudio)
        self.actionSVM.setObjectName(u"actionSVM")
        self.actionSVM.setMenuRole(QAction.MenuRole.NoRole)
        self.actionResetSVM = QAction(MainWindowAudio)
        self.actionResetSVM.setObjectName(u"actionResetSVM")
        self.actionResetSVM.setMenuRole(QAction.MenuRole.NoRole)
        self.actionInfo = QAction(MainWindowAudio)
        self.actionInfo.setObjectName(u"actionInfo")
        self.actionInfo.setMenuRole(QAction.MenuRole.NoRole)
        self.actionVersion = QAction(MainWindowAudio)
        self.actionVersion.setObjectName(u"actionVersion")
        self.actionVersion.setMenuRole(QAction.MenuRole.NoRole)
        self.actionWebSite = QAction(MainWindowAudio)
        self.actionWebSite.setObjectName(u"actionWebSite")
        self.actionWebSite.setMenuRole(QAction.MenuRole.NoRole)
        self.actionLicense = QAction(MainWindowAudio)
        self.actionLicense.setObjectName(u"actionLicense")
        self.actionLicense.setMenuRole(QAction.MenuRole.NoRole)
        self.actionStart = QAction(MainWindowAudio)
        self.actionStart.setObjectName(u"actionStart")
        self.actionStart.setMenuRole(QAction.MenuRole.NoRole)
        self.actionClear = QAction(MainWindowAudio)
        self.actionClear.setObjectName(u"actionClear")
        icon7 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.SyncSynchronizing))
        self.actionClear.setIcon(icon7)
        self.actionClear.setMenuRole(QAction.MenuRole.NoRole)
        self.actionReplay = QAction(MainWindowAudio)
        self.actionReplay.setObjectName(u"actionReplay")
        self.actionReplay.setMenuRole(QAction.MenuRole.NoRole)
        self.actionAbout = QAction(MainWindowAudio)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionAbout.setMenuRole(QAction.MenuRole.AboutRole)
        self.actionDocumentation = QAction(MainWindowAudio)
        self.actionDocumentation.setObjectName(u"actionDocumentation")
        self.actionDocumentation.setMenuRole(QAction.MenuRole.NoRole)
        self.actionQuit = QAction(MainWindowAudio)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionQuit.setMenuRole(QAction.MenuRole.QuitRole)
        self.actionDark = QAction(MainWindowAudio)
        self.actionDark.setObjectName(u"actionDark")
        self.actionDark_Green = QAction(MainWindowAudio)
        self.actionDark_Green.setObjectName(u"actionDark_Green")
        self.actionDark_Blue = QAction(MainWindowAudio)
        self.actionDark_Blue.setObjectName(u"actionDark_Blue")
        self.actionDark_Amber = QAction(MainWindowAudio)
        self.actionDark_Amber.setObjectName(u"actionDark_Amber")
        self.actionLight = QAction(MainWindowAudio)
        self.actionLight.setObjectName(u"actionLight")
        self.actionLight_Green = QAction(MainWindowAudio)
        self.actionLight_Green.setObjectName(u"actionLight_Green")
        self.actionLight_Blue = QAction(MainWindowAudio)
        self.actionLight_Blue.setObjectName(u"actionLight_Blue")
        self.actionLight_Amber = QAction(MainWindowAudio)
        self.actionLight_Amber.setObjectName(u"actionLight_Amber")
        self.actionVery_Small = QAction(MainWindowAudio)
        self.actionVery_Small.setObjectName(u"actionVery_Small")
        self.actionSmall = QAction(MainWindowAudio)
        self.actionSmall.setObjectName(u"actionSmall")
        self.actionMedium = QAction(MainWindowAudio)
        self.actionMedium.setObjectName(u"actionMedium")
        self.actionLarge = QAction(MainWindowAudio)
        self.actionLarge.setObjectName(u"actionLarge")
        self.centralWidgetAudio = QWidget(MainWindowAudio)
        self.centralWidgetAudio.setObjectName(u"centralWidgetAudio")
        self.centralWidgetAudio.setEnabled(True)
        sizePolicy.setHeightForWidth(self.centralWidgetAudio.sizePolicy().hasHeightForWidth())
        self.centralWidgetAudio.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QVBoxLayout(self.centralWidgetAudio)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(10, 0, 10, 10)
        self.mainWidget = QWidget(self.centralWidgetAudio)
        self.mainWidget.setObjectName(u"mainWidget")
        self.verticalLayout_3 = QVBoxLayout(self.mainWidget)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.mainSplitter = QSplitter(self.mainWidget)
        self.mainSplitter.setObjectName(u"mainSplitter")
        sizePolicy.setHeightForWidth(self.mainSplitter.sizePolicy().hasHeightForWidth())
        self.mainSplitter.setSizePolicy(sizePolicy)
        self.mainSplitter.setOrientation(Qt.Orientation.Horizontal)
        self.mainSplitter.setChildrenCollapsible(False)
        self.graphsSplitter = QSplitter(self.mainSplitter)
        self.graphsSplitter.setObjectName(u"graphsSplitter")
        sizePolicy.setHeightForWidth(self.graphsSplitter.sizePolicy().hasHeightForWidth())
        self.graphsSplitter.setSizePolicy(sizePolicy)
        self.graphsSplitter.setOrientation(Qt.Orientation.Vertical)
        self.graphsSplitter.setChildrenCollapsible(False)
        self.IFFTPlotFrame = QFrame(self.graphsSplitter)
        self.IFFTPlotFrame.setObjectName(u"IFFTPlotFrame")
        sizePolicy.setHeightForWidth(self.IFFTPlotFrame.sizePolicy().hasHeightForWidth())
        self.IFFTPlotFrame.setSizePolicy(sizePolicy)
        self.IFFTPlotFrame.setFrameShape(QFrame.Shape.Box)
        self.IFFTPlotFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.IFFTPlotVLayout = QVBoxLayout(self.IFFTPlotFrame)
        self.IFFTPlotVLayout.setObjectName(u"IFFTPlotVLayout")
        self.IFFTTitleLabel = QLabel(self.IFFTPlotFrame)
        self.IFFTTitleLabel.setObjectName(u"IFFTTitleLabel")
        font2 = QFont()
        font2.setPointSize(14)
        self.IFFTTitleLabel.setFont(font2)
        self.IFFTTitleLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.IFFTPlotVLayout.addWidget(self.IFFTTitleLabel)

        self.IFFTPlotWidget = QWidget(self.IFFTPlotFrame)
        self.IFFTPlotWidget.setObjectName(u"IFFTPlotWidget")
        sizePolicy.setHeightForWidth(self.IFFTPlotWidget.sizePolicy().hasHeightForWidth())
        self.IFFTPlotWidget.setSizePolicy(sizePolicy)
        self.IFFTPlotWidget.setMinimumSize(QSize(420, 160))

        self.IFFTPlotVLayout.addWidget(self.IFFTPlotWidget)

        self.graphsSplitter.addWidget(self.IFFTPlotFrame)
        self.FFTPlotFrame = QFrame(self.graphsSplitter)
        self.FFTPlotFrame.setObjectName(u"FFTPlotFrame")
        self.FFTPlotFrame.setEnabled(True)
        sizePolicy.setHeightForWidth(self.FFTPlotFrame.sizePolicy().hasHeightForWidth())
        self.FFTPlotFrame.setSizePolicy(sizePolicy)
        self.FFTPlotFrame.setFrameShape(QFrame.Shape.Box)
        self.FFTPlotFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.FFTPlotVLayout = QVBoxLayout(self.FFTPlotFrame)
        self.FFTPlotVLayout.setObjectName(u"FFTPlotVLayout")
        self.FFTModeHLayout = QHBoxLayout()
        self.FFTModeHLayout.setObjectName(u"FFTModeHLayout")
        self.FFTModeHLayout.setContentsMargins(0, 0, 0, 0)
        self.FFTModeLabel = QLabel(self.FFTPlotFrame)
        self.FFTModeLabel.setObjectName(u"FFTModeLabel")
        self.FFTModeLabel.setFont(font2)

        self.FFTModeHLayout.addWidget(self.FFTModeLabel)

        self.FFTModeComboBox = QComboBox(self.FFTPlotFrame)
        self.FFTModeComboBox.addItem("")
        self.FFTModeComboBox.addItem("")
        self.FFTModeComboBox.setObjectName(u"FFTModeComboBox")
        self.FFTModeComboBox.setFont(font2)

        self.FFTModeHLayout.addWidget(self.FFTModeComboBox)

        self.FFTModeHLayout.addStretch(1)

        self.FFTPlotVLayout.addLayout(self.FFTModeHLayout)

        self.FFTPotWidget = QWidget(self.FFTPlotFrame)
        self.FFTPotWidget.setObjectName(u"FFTPotWidget")
        sizePolicy.setHeightForWidth(self.FFTPotWidget.sizePolicy().hasHeightForWidth())
        self.FFTPotWidget.setSizePolicy(sizePolicy)
        self.FFTPotWidget.setMinimumSize(QSize(420, 200))

        self.FFTPlotVLayout.addWidget(self.FFTPotWidget)

        self.graphsSplitter.addWidget(self.FFTPlotFrame)
        self.graphsSplitter.setStretchFactor(0, 2)
        self.graphsSplitter.setStretchFactor(1, 3)
        self.graphsSplitter.setSizes([280, 420])

        self.mainSplitter.addWidget(self.graphsSplitter)
        self.rightPanel = QWidget(self.mainSplitter)
        self.rightPanel.setObjectName(u"rightPanel")
        sizePolicy.setHeightForWidth(self.rightPanel.sizePolicy().hasHeightForWidth())
        self.rightPanel.setSizePolicy(sizePolicy)
        self.rightPanel.setMinimumWidth(620)
        self.rightPanelVLayout = QVBoxLayout(self.rightPanel)
        self.rightPanelVLayout.setObjectName(u"rightPanelVLayout")
        self.rightPanelVLayout.setContentsMargins(0, 0, 0, 0)
        self.FFTClicksDetectedLabel = QLabel(self.rightPanel)
        self.FFTClicksDetectedLabel.setObjectName(u"FFTClicksDetectedLabel")
        font1 = QFont()
        font1.setPointSize(21)
        font1.setBold(True)
        self.FFTClicksDetectedLabel.setFont(font1)
        self.FFTClicksDetectedLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.rightPanelVLayout.addWidget(self.FFTClicksDetectedLabel)

        self.FFTClicksDetectedTableWidget = QTableWidget(self.rightPanel)
        if (self.FFTClicksDetectedTableWidget.columnCount() < 5):
            self.FFTClicksDetectedTableWidget.setColumnCount(5)
        self.FFTClicksDetectedTableWidget.setObjectName(u"FFTClicksDetectedTableWidget")
        self.FFTClicksDetectedTableWidget.setColumnCount(5)
        sizePolicy.setHeightForWidth(self.FFTClicksDetectedTableWidget.sizePolicy().hasHeightForWidth())
        self.FFTClicksDetectedTableWidget.setSizePolicy(sizePolicy)

        self.rightPanelVLayout.addWidget(self.FFTClicksDetectedTableWidget)

        self.FFTInfoGroupBox = QGroupBox(self.rightPanel)
        self.FFTInfoGroupBox.setObjectName(u"FFTInfoGroupBox")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.FFTInfoGroupBox.sizePolicy().hasHeightForWidth())
        self.FFTInfoGroupBox.setSizePolicy(sizePolicy1)
        self.FFTInfoGroupBox.setMaximumSize(QSize(16777215, 70))
        self.FFTInfoGroupBox.setFont(font2)
        self.FFTInfoGroupBox.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.horizontalLayout_2 = QHBoxLayout(self.FFTInfoGroupBox)
#ifndef Q_OS_MAC
        self.horizontalLayout_2.setSpacing(-1)
#endif
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setSizeConstraint(QLayout.SizeConstraint.SetMinimumSize)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)

        self.horizontalLayout_2.addStretch(1)

        self.FFTStartStopButton = QPushButton(self.FFTInfoGroupBox)
        self.FFTStartStopButton.setObjectName(u"FFTStartStopButton")
        self.FFTStartStopButton.setEnabled(True)
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.FFTStartStopButton.sizePolicy().hasHeightForWidth())
        self.FFTStartStopButton.setSizePolicy(sizePolicy2)
        self.FFTStartStopButton.setMinimumSize(QSize(180, 20))
        self.FFTStartStopButton.setMaximumSize(QSize(16777215, 35))
        font3 = QFont()
        font3.setPointSize(18)
        font3.setBold(True)
        self.FFTStartStopButton.setFont(font3)
        self.FFTStartStopButton.setCheckable(True)
        self.FFTStartStopButton.setChecked(False)

        self.horizontalLayout_2.addWidget(self.FFTStartStopButton)

        self.FFTInfoFrame2 = QFrame(self.FFTInfoGroupBox)
        self.FFTInfoFrame2.setObjectName(u"FFTInfoFrame2")
        self.FFTInfoFrame2.setFrameShape(QFrame.Shape.VLine)
        self.FFTInfoFrame2.setFrameShadow(QFrame.Shadow.Raised)

        self.horizontalLayout_2.addWidget(self.FFTInfoFrame2)

        self.FFTClicksDetectorHLayout = QHBoxLayout()
        self.FFTClicksDetectorHLayout.setSpacing(5)
        self.FFTClicksDetectorHLayout.setObjectName(u"FFTClicksDetectorHLayout")
        self.FFTClicksDetectorHLayout.setSizeConstraint(QLayout.SizeConstraint.SetMinimumSize)
        self.FFTClicksDetectorHLayout.setContentsMargins(5, -1, 5, -1)
        self.FFTClicksDetectorLabel = QLabel(self.FFTInfoGroupBox)
        self.FFTClicksDetectorLabel.setObjectName(u"FFTClicksDetectorLabel")
        sizePolicy2.setHeightForWidth(self.FFTClicksDetectorLabel.sizePolicy().hasHeightForWidth())
        self.FFTClicksDetectorLabel.setSizePolicy(sizePolicy2)
        self.FFTClicksDetectorLabel.setMinimumSize(QSize(130, 0))
        font5 = QFont()
        font5.setPointSize(18)
        font5.setWeight(QFont.Medium)
        font5.setItalic(False)
        font5.setUnderline(False)
        font5.setStrikeOut(False)
        self.FFTClicksDetectorLabel.setFont(font5)
        self.FFTClicksDetectorLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.FFTClicksDetectorHLayout.addWidget(self.FFTClicksDetectorLabel)

        self.FFTClicksDetectorButton = QPushButton(self.FFTInfoGroupBox)
        self.FFTClicksDetectorButton.setObjectName(u"FFTClicksDetectorButton")
        sizePolicy2.setHeightForWidth(self.FFTClicksDetectorButton.sizePolicy().hasHeightForWidth())
        self.FFTClicksDetectorButton.setSizePolicy(sizePolicy2)
        self.FFTClicksDetectorButton.setMinimumSize(QSize(80, 20))
        self.FFTClicksDetectorButton.setMaximumSize(QSize(16777215, 35))
        font4 = QFont()
        font4.setPointSize(18)
        font4.setWeight(QFont.Medium)
        self.FFTClicksDetectorButton.setFont(font4)
        self.FFTClicksDetectorButton.setCheckable(True)
        self.FFTClicksDetectorButton.setChecked(True)

        self.FFTClicksDetectorHLayout.addWidget(self.FFTClicksDetectorButton)

        self.horizontalLayout_2.addLayout(self.FFTClicksDetectorHLayout)

        self.FFTInfoFrame3 = QFrame(self.FFTInfoGroupBox)
        self.FFTInfoFrame3.setObjectName(u"FFTInfoFrame3")
        self.FFTInfoFrame3.setFrameShape(QFrame.Shape.VLine)
        self.FFTInfoFrame3.setFrameShadow(QFrame.Shadow.Raised)

        self.horizontalLayout_2.addWidget(self.FFTInfoFrame3)

        self.FFTTimePassedHLayout = QHBoxLayout()
#ifndef Q_OS_MAC
        self.FFTTimePassedHLayout.setSpacing(-1)
#endif
        self.FFTTimePassedHLayout.setObjectName(u"FFTTimePassedHLayout")
        self.FFTTimePassedHLayout.setSizeConstraint(QLayout.SizeConstraint.SetMinimumSize)
        self.FFTTimePassedHLayout.setContentsMargins(5, -1, 5, -1)
        self.FFTTimePassedLabel = QLabel(self.FFTInfoGroupBox)
        self.FFTTimePassedLabel.setObjectName(u"FFTTimePassedLabel")
        sizePolicy2.setHeightForWidth(self.FFTTimePassedLabel.sizePolicy().hasHeightForWidth())
        self.FFTTimePassedLabel.setSizePolicy(sizePolicy2)
        self.FFTTimePassedLabel.setMinimumSize(QSize(110, 0))
        self.FFTTimePassedLabel.setMaximumSize(QSize(110, 16777215))
        font6 = QFont()
        font6.setPointSize(18)
        font6.setWeight(QFont.Medium)
        font6.setItalic(False)
        font6.setKerning(True)
        self.FFTTimePassedLabel.setFont(font6)
        self.FFTTimePassedLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.FFTTimePassedHLayout.addWidget(self.FFTTimePassedLabel)

        self.FFTTimePassedLabelTime = QLabel(self.FFTInfoGroupBox)
        self.FFTTimePassedLabelTime.setObjectName(u"FFTTimePassedLabelTime")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.FFTTimePassedLabelTime.sizePolicy().hasHeightForWidth())
        self.FFTTimePassedLabelTime.setSizePolicy(sizePolicy3)
        self.FFTTimePassedLabelTime.setMinimumSize(QSize(120, 0))
        self.FFTTimePassedLabelTime.setMaximumSize(QSize(120, 16777215))
        self.FFTTimePassedLabelTime.setFont(font)
        self.FFTTimePassedLabelTime.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.FFTTimePassedLabelTime.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.FFTTimePassedHLayout.addWidget(self.FFTTimePassedLabelTime)

        self.horizontalLayout_2.addLayout(self.FFTTimePassedHLayout)

        self.horizontalLayout_2.addStretch(1)

        self.rightPanelVLayout.addWidget(self.FFTInfoGroupBox)

        self.mainSplitter.addWidget(self.rightPanel)
        self.mainSplitter.setStretchFactor(0, 1)
        self.mainSplitter.setStretchFactor(1, 1)
        self.mainSplitter.setSizes([620, 660])

        self.verticalLayout_3.addWidget(self.mainSplitter)


        self.verticalLayout_2.addWidget(self.mainWidget)

        MainWindowAudio.setCentralWidget(self.centralWidgetAudio)
        self.menuBar = QMenuBar(MainWindowAudio)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1280, 23))
        font7 = QFont()
        font7.setPointSize(12)
        font7.setBold(False)
        self.menuBar.setFont(font7)
        self.menuPlantLeaf = QMenu(self.menuBar)
        self.menuPlantLeaf.setObjectName(u"menuPlantLeaf")
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuExperiment = QMenu(self.menuBar)
        self.menuExperiment.setObjectName(u"menuExperiment")
        self.menuSettings = QMenu(self.menuBar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuChoose_Theme = QMenu(self.menuSettings)
        self.menuChoose_Theme.setObjectName(u"menuChoose_Theme")
        self.menuChoose_Font_Scale = QMenu(self.menuSettings)
        self.menuChoose_Font_Scale.setObjectName(u"menuChoose_Font_Scale")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindowAudio.setMenuBar(self.menuBar)
        self.toolBar = QToolBar(MainWindowAudio)
        self.toolBar.setObjectName(u"toolBar")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy4)
        font8 = QFont()
        font8.setPointSize(13)
        self.toolBar.setFont(font8)
        self.toolBar.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(Qt.ToolBarArea.TopToolBarArea)
        self.toolBar.setOrientation(Qt.Orientation.Horizontal)
        self.toolBar.setIconSize(QSize(32, 32))
        self.toolBar.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindowAudio.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuExperiment.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuBar.addAction(self.menuPlantLeaf.menuAction())
        self.menuPlantLeaf.addAction(self.actionHome)
        self.menuPlantLeaf.addAction(self.actionQuit)
        self.menuPlantLeaf.addSeparator()
        self.menuPlantLeaf.addAction(self.actionInfo)
        self.menuPlantLeaf.addAction(self.actionVersion)
        self.menuPlantLeaf.addAction(self.actionWebSite)
        self.menuPlantLeaf.addAction(self.actionLicense)
        self.menuFile.addAction(self.actionNewFile)
        self.menuFile.addAction(self.actionOpenFile)
        self.menuFile.addAction(self.actionSave)
        self.menuExperiment.addAction(self.actionStart)
        self.menuExperiment.addAction(self.actionClear)
        self.menuExperiment.addAction(self.actionReplay)
        self.menuExperiment.addSeparator()
        self.menuExperiment.addAction(self.actionSerialPort)
        self.menuExperiment.addAction(self.actionSamplingSettings)
        self.menuExperiment.addSeparator()
        self.menuExperiment.addAction(self.actionSVM)
        self.menuExperiment.addAction(self.actionResetSVM)
        self.menuSettings.addAction(self.menuChoose_Theme.menuAction())
        self.menuSettings.addAction(self.menuChoose_Font_Scale.menuAction())
        self.menuChoose_Theme.addAction(self.actionDark)
        self.menuChoose_Theme.addAction(self.actionDark_Green)
        self.menuChoose_Theme.addAction(self.actionDark_Blue)
        self.menuChoose_Theme.addAction(self.actionDark_Amber)
        self.menuChoose_Theme.addSeparator()
        self.menuChoose_Theme.addAction(self.actionLight)
        self.menuChoose_Theme.addAction(self.actionLight_Green)
        self.menuChoose_Theme.addAction(self.actionLight_Blue)
        self.menuChoose_Theme.addAction(self.actionLight_Amber)
        self.menuChoose_Font_Scale.addAction(self.actionVery_Small)
        self.menuChoose_Font_Scale.addAction(self.actionSmall)
        self.menuChoose_Font_Scale.addAction(self.actionMedium)
        self.menuChoose_Font_Scale.addAction(self.actionLarge)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionDocumentation)
        self.toolBar.addAction(self.actionHome)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNewFile)
        self.toolBar.addAction(self.actionOpenFile)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClear)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSerialPort)
        self.toolBar.addAction(self.actionViewGrid)
        self.toolBar.addAction(self.actionSamplingSettings)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSVM)

        self.retranslateUi(MainWindowAudio)

        QMetaObject.connectSlotsByName(MainWindowAudio)
    # setupUi

    def retranslateUi(self, MainWindowAudio):
        MainWindowAudio.setWindowTitle(QCoreApplication.translate("MainWindowAudio", u"MainWindow", None))
        self.actionNewFile.setText(QCoreApplication.translate("MainWindowAudio", u"New File", None))
#if QT_CONFIG(tooltip)
        self.actionNewFile.setToolTip(QCoreApplication.translate("MainWindowAudio", u"New File", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionNewFile.setShortcut(QCoreApplication.translate("MainWindowAudio", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpenFile.setText(QCoreApplication.translate("MainWindowAudio", u"Open File", None))
#if QT_CONFIG(tooltip)
        self.actionOpenFile.setToolTip(QCoreApplication.translate("MainWindowAudio", u"Open...", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionOpenFile.setShortcut(QCoreApplication.translate("MainWindowAudio", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("MainWindowAudio", u"Save As", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("MainWindowAudio", u"Save As...", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindowAudio", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionHome.setText(QCoreApplication.translate("MainWindowAudio", u"Home", None))
#if QT_CONFIG(tooltip)
        self.actionHome.setToolTip(QCoreApplication.translate("MainWindowAudio", u"Home", None))
#endif // QT_CONFIG(tooltip)
        self.actionSerialPort.setText(QCoreApplication.translate("MainWindowAudio", u"Serial Port", None))
#if QT_CONFIG(tooltip)
        self.actionSerialPort.setToolTip(QCoreApplication.translate("MainWindowAudio", u"Choose Serial Port", None))
#endif // QT_CONFIG(tooltip)
        self.actionViewGrid.setText(QCoreApplication.translate("MainWindowAudio", u"View Grid", None))
#if QT_CONFIG(tooltip)
        self.actionViewGrid.setToolTip(QCoreApplication.translate("MainWindowAudio", u"View Grid", None))
#endif // QT_CONFIG(tooltip)
        self.actionSamplingSettings.setText(QCoreApplication.translate("MainWindowAudio", u"Sampling Settings", None))
#if QT_CONFIG(tooltip)
        self.actionSamplingSettings.setToolTip(QCoreApplication.translate("MainWindowAudio", u"Sampling Settings", None))
#endif // QT_CONFIG(tooltip)
        self.actionSVM.setText(QCoreApplication.translate("MainWindowAudio", u"Select SVM Model", None))
#if QT_CONFIG(tooltip)
        self.actionSVM.setToolTip(QCoreApplication.translate("MainWindowAudio", u"Choose the .pkl model to classify with", None))
#endif // QT_CONFIG(tooltip)
        self.actionResetSVM.setText(QCoreApplication.translate("MainWindowAudio", u"Reset to shipped v6 model", None))
        self.actionInfo.setText(QCoreApplication.translate("MainWindowAudio", u"Info", None))
        self.actionVersion.setText(QCoreApplication.translate("MainWindowAudio", u"Version", None))
        self.actionWebSite.setText(QCoreApplication.translate("MainWindowAudio", u"WebSite", None))
        self.actionLicense.setText(QCoreApplication.translate("MainWindowAudio", u"License", None))
        self.actionStart.setText(QCoreApplication.translate("MainWindowAudio", u"Start/Stop", None))
        self.actionClear.setText(QCoreApplication.translate("MainWindowAudio", u"Clear", None))
        self.actionReplay.setText(QCoreApplication.translate("MainWindowAudio", u"Replay", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindowAudio", u"About...", None))
        self.actionDocumentation.setText(QCoreApplication.translate("MainWindowAudio", u"Documentation", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindowAudio", u"Quit", None))
        self.actionDark.setText(QCoreApplication.translate("MainWindowAudio", u"Dark", None))
        self.actionDark_Green.setText(QCoreApplication.translate("MainWindowAudio", u"Dark Green", None))
        self.actionDark_Blue.setText(QCoreApplication.translate("MainWindowAudio", u"Dark Blue", None))
        self.actionDark_Amber.setText(QCoreApplication.translate("MainWindowAudio", u"Dark Amber", None))
        self.actionLight.setText(QCoreApplication.translate("MainWindowAudio", u"Light", None))
        self.actionLight_Green.setText(QCoreApplication.translate("MainWindowAudio", u"Light Green", None))
        self.actionLight_Blue.setText(QCoreApplication.translate("MainWindowAudio", u"Light Blue", None))
        self.actionLight_Amber.setText(QCoreApplication.translate("MainWindowAudio", u"Light Amber", None))
        self.actionVery_Small.setText(QCoreApplication.translate("MainWindowAudio", u"Very Small", None))
        self.actionSmall.setText(QCoreApplication.translate("MainWindowAudio", u"Small", None))
        self.actionMedium.setText(QCoreApplication.translate("MainWindowAudio", u"Medium", None))
        self.actionLarge.setText(QCoreApplication.translate("MainWindowAudio", u"Large", None))
        self.IFFTTitleLabel.setText(QCoreApplication.translate("MainWindowAudio", u"iFFT \u2014 no event", None))
        self.FFTModeLabel.setText(QCoreApplication.translate("MainWindowAudio", u"Spectrum:", None))
        self.FFTModeComboBox.setItemText(0, QCoreApplication.translate("MainWindowAudio", u"Frame FFT (transmitted)", None))
        self.FFTModeComboBox.setItemText(1, QCoreApplication.translate("MainWindowAudio", u"Region FFT (click)", None))
        self.FFTClicksDetectedLabel.setText(QCoreApplication.translate("MainWindowAudio", u"Events", None))
        self.FFTInfoGroupBox.setTitle("")
        self.FFTStartStopButton.setText(QCoreApplication.translate("MainWindowAudio", u"START", None))
        self.FFTClicksDetectorLabel.setText(QCoreApplication.translate("MainWindowAudio", u"Clicks detection:", None))
        self.FFTClicksDetectorButton.setText(QCoreApplication.translate("MainWindowAudio", u"ON", None))
        self.FFTTimePassedLabel.setText(QCoreApplication.translate("MainWindowAudio", u"Time Passed", None))
        self.FFTTimePassedLabelTime.setText(QCoreApplication.translate("MainWindowAudio", u"0:00:00", None))
        self.menuPlantLeaf.setTitle(QCoreApplication.translate("MainWindowAudio", u"About", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindowAudio", u"File", None))
        self.menuExperiment.setTitle(QCoreApplication.translate("MainWindowAudio", u"Experiment", None))
        self.menuSettings.setTitle(QCoreApplication.translate("MainWindowAudio", u"Settings", None))
        self.menuChoose_Theme.setTitle(QCoreApplication.translate("MainWindowAudio", u"Choose Theme", None))
        self.menuChoose_Font_Scale.setTitle(QCoreApplication.translate("MainWindowAudio", u"Choose Font Scale", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindowAudio", u"Help", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindowAudio", u"toolBar", None))
    # retranslateUi

