# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindowVoltage.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QHBoxLayout,
    QLabel, QLayout, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QToolBar,
    QVBoxLayout, QWidget)

class Ui_MainWindowVoltage(object):
    def setupUi(self, MainWindowVoltage):
        if not MainWindowVoltage.objectName():
            MainWindowVoltage.setObjectName(u"MainWindowVoltage")
        MainWindowVoltage.setEnabled(True)
        MainWindowVoltage.resize(1280, 720)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindowVoltage.sizePolicy().hasHeightForWidth())
        MainWindowVoltage.setSizePolicy(sizePolicy)
        MainWindowVoltage.setMinimumSize(QSize(1104, 576))
        font = QFont()
        font.setPointSize(18)
        MainWindowVoltage.setFont(font)
        self.actionNewFile = QAction(MainWindowVoltage)
        self.actionNewFile.setObjectName(u"actionNewFile")
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentNew))
        self.actionNewFile.setIcon(icon)
        self.actionNewFile.setMenuRole(QAction.MenuRole.NoRole)
        self.actionOpenFile = QAction(MainWindowVoltage)
        self.actionOpenFile.setObjectName(u"actionOpenFile")
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentOpen))
        self.actionOpenFile.setIcon(icon1)
        self.actionOpenFile.setMenuRole(QAction.MenuRole.NoRole)
        self.actionSave = QAction(MainWindowVoltage)
        self.actionSave.setObjectName(u"actionSave")
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSave))
        self.actionSave.setIcon(icon2)
        self.actionSave.setMenuRole(QAction.MenuRole.NoRole)
        self.actionHome = QAction(MainWindowVoltage)
        self.actionHome.setObjectName(u"actionHome")
        icon3 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoHome))
        self.actionHome.setIcon(icon3)
        self.actionHome.setMenuRole(QAction.MenuRole.NoRole)
        self.actionHome.setIconVisibleInMenu(False)
        self.actionSerialPort = QAction(MainWindowVoltage)
        self.actionSerialPort.setObjectName(u"actionSerialPort")
        icon4 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.SoftwareUpdateAvailable))
        self.actionSerialPort.setIcon(icon4)
        self.actionSerialPort.setMenuRole(QAction.MenuRole.NoRole)
        self.actionViewGrid = QAction(MainWindowVoltage)
        self.actionViewGrid.setObjectName(u"actionViewGrid")
        icon5 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.Computer))
        self.actionViewGrid.setIcon(icon5)
        self.actionViewGrid.setMenuRole(QAction.MenuRole.NoRole)
        self.actionSamplingSettings = QAction(MainWindowVoltage)
        self.actionSamplingSettings.setObjectName(u"actionSamplingSettings")
        icon6 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentPageSetup))
        self.actionSamplingSettings.setIcon(icon6)
        self.actionSamplingSettings.setMenuRole(QAction.MenuRole.NoRole)
        self.actionInfo = QAction(MainWindowVoltage)
        self.actionInfo.setObjectName(u"actionInfo")
        self.actionInfo.setMenuRole(QAction.MenuRole.NoRole)
        self.actionVersion = QAction(MainWindowVoltage)
        self.actionVersion.setObjectName(u"actionVersion")
        self.actionVersion.setMenuRole(QAction.MenuRole.NoRole)
        self.actionWebSite = QAction(MainWindowVoltage)
        self.actionWebSite.setObjectName(u"actionWebSite")
        self.actionWebSite.setMenuRole(QAction.MenuRole.NoRole)
        self.actionLicense = QAction(MainWindowVoltage)
        self.actionLicense.setObjectName(u"actionLicense")
        self.actionLicense.setMenuRole(QAction.MenuRole.NoRole)
        self.actionStart = QAction(MainWindowVoltage)
        self.actionStart.setObjectName(u"actionStart")
        self.actionStart.setMenuRole(QAction.MenuRole.NoRole)
        self.actionClear = QAction(MainWindowVoltage)
        self.actionClear.setObjectName(u"actionClear")
        icon7 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.SyncSynchronizing))
        self.actionClear.setIcon(icon7)
        self.actionClear.setMenuRole(QAction.MenuRole.NoRole)
        self.actionReplay = QAction(MainWindowVoltage)
        self.actionReplay.setObjectName(u"actionReplay")
        self.actionReplay.setMenuRole(QAction.MenuRole.NoRole)
        self.actionAbout = QAction(MainWindowVoltage)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionAbout.setMenuRole(QAction.MenuRole.AboutRole)
        self.actionDocumentation = QAction(MainWindowVoltage)
        self.actionDocumentation.setObjectName(u"actionDocumentation")
        self.actionDocumentation.setMenuRole(QAction.MenuRole.NoRole)
        self.actionQuit = QAction(MainWindowVoltage)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionQuit.setMenuRole(QAction.MenuRole.QuitRole)
        self.actionDark = QAction(MainWindowVoltage)
        self.actionDark.setObjectName(u"actionDark")
        self.actionDark_Green = QAction(MainWindowVoltage)
        self.actionDark_Green.setObjectName(u"actionDark_Green")
        self.actionDark_Blue = QAction(MainWindowVoltage)
        self.actionDark_Blue.setObjectName(u"actionDark_Blue")
        self.actionDark_Amber = QAction(MainWindowVoltage)
        self.actionDark_Amber.setObjectName(u"actionDark_Amber")
        self.actionLight = QAction(MainWindowVoltage)
        self.actionLight.setObjectName(u"actionLight")
        self.actionLight_Green = QAction(MainWindowVoltage)
        self.actionLight_Green.setObjectName(u"actionLight_Green")
        self.actionLight_Blue = QAction(MainWindowVoltage)
        self.actionLight_Blue.setObjectName(u"actionLight_Blue")
        self.actionLight_Amber = QAction(MainWindowVoltage)
        self.actionLight_Amber.setObjectName(u"actionLight_Amber")
        self.actionVery_Small = QAction(MainWindowVoltage)
        self.actionVery_Small.setObjectName(u"actionVery_Small")
        self.actionSmall = QAction(MainWindowVoltage)
        self.actionSmall.setObjectName(u"actionSmall")
        self.actionMedium = QAction(MainWindowVoltage)
        self.actionMedium.setObjectName(u"actionMedium")
        self.actionLarge = QAction(MainWindowVoltage)
        self.actionLarge.setObjectName(u"actionLarge")
        self.actionUpdatedTimeWindow = QAction(MainWindowVoltage)
        self.actionUpdatedTimeWindow.setObjectName(u"actionUpdatedTimeWindow")
        icon8 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.VideoDisplay))
        self.actionUpdatedTimeWindow.setIcon(icon8)
        self.actionUpdatedTimeWindow.setMenuRole(QAction.MenuRole.NoRole)
        self.centralWidgetVoltage = QWidget(MainWindowVoltage)
        self.centralWidgetVoltage.setObjectName(u"centralWidgetVoltage")
        self.centralWidgetVoltage.setEnabled(True)
        sizePolicy.setHeightForWidth(self.centralWidgetVoltage.sizePolicy().hasHeightForWidth())
        self.centralWidgetVoltage.setSizePolicy(sizePolicy)
        self.verticalLayout_4 = QVBoxLayout(self.centralWidgetVoltage)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.plotVLayout = QVBoxLayout()
        self.plotVLayout.setObjectName(u"plotVLayout")
        self.plotFrame = QFrame(self.centralWidgetVoltage)
        self.plotFrame.setObjectName(u"plotFrame")
        self.plotFrame.setEnabled(True)
        sizePolicy.setHeightForWidth(self.plotFrame.sizePolicy().hasHeightForWidth())
        self.plotFrame.setSizePolicy(sizePolicy)
        self.plotFrame.setFrameShape(QFrame.Shape.Box)
        self.plotFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.plotFrame)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.plotWidget = QWidget(self.plotFrame)
        self.plotWidget.setObjectName(u"plotWidget")
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setMinimumSize(QSize(625, 245))

        self.horizontalLayout_2.addWidget(self.plotWidget)


        self.plotVLayout.addWidget(self.plotFrame)


        self.verticalLayout_4.addLayout(self.plotVLayout)

        self.infoGroupBox = QGroupBox(self.centralWidgetVoltage)
        self.infoGroupBox.setObjectName(u"infoGroupBox")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.infoGroupBox.sizePolicy().hasHeightForWidth())
        self.infoGroupBox.setSizePolicy(sizePolicy1)
        self.infoGroupBox.setMaximumSize(QSize(1260, 70))
        font1 = QFont()
        font1.setPointSize(14)
        self.infoGroupBox.setFont(font1)
        self.infoGroupBox.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.horizontalLayout = QHBoxLayout(self.infoGroupBox)
#ifndef Q_OS_MAC
        self.horizontalLayout.setSpacing(-1)
#endif
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SizeConstraint.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(20, 0, 20, 0)
        self.startStopButton = QPushButton(self.infoGroupBox)
        self.startStopButton.setObjectName(u"startStopButton")
        self.startStopButton.setEnabled(True)
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.startStopButton.sizePolicy().hasHeightForWidth())
        self.startStopButton.setSizePolicy(sizePolicy2)
        self.startStopButton.setMinimumSize(QSize(180, 20))
        self.startStopButton.setMaximumSize(QSize(16777215, 35))
        font2 = QFont()
        font2.setPointSize(21)
        font2.setBold(True)
        self.startStopButton.setFont(font2)
        self.startStopButton.setCheckable(True)
        self.startStopButton.setChecked(False)

        self.horizontalLayout.addWidget(self.startStopButton)

        self.info_frame_1 = QFrame(self.infoGroupBox)
        self.info_frame_1.setObjectName(u"info_frame_1")
        self.info_frame_1.setFrameShape(QFrame.Shape.VLine)
        self.info_frame_1.setFrameShadow(QFrame.Shadow.Raised)

        self.horizontalLayout.addWidget(self.info_frame_1)

        self.signalStabilityHLayout = QHBoxLayout()
        self.signalStabilityHLayout.setSpacing(0)
        self.signalStabilityHLayout.setObjectName(u"signalStabilityHLayout")
        self.signalStabilityHLayout.setSizeConstraint(QLayout.SizeConstraint.SetMinimumSize)
        self.signalStabilityLabelWritten = QLabel(self.infoGroupBox)
        self.signalStabilityLabelWritten.setObjectName(u"signalStabilityLabelWritten")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.signalStabilityLabelWritten.sizePolicy().hasHeightForWidth())
        self.signalStabilityLabelWritten.setSizePolicy(sizePolicy3)
        self.signalStabilityLabelWritten.setMinimumSize(QSize(140, 0))
        font3 = QFont()
        font3.setPointSize(18)
        font3.setWeight(QFont.Medium)
        font3.setItalic(False)
        self.signalStabilityLabelWritten.setFont(font3)
        self.signalStabilityLabelWritten.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.signalStabilityHLayout.addWidget(self.signalStabilityLabelWritten)

        self.boxFrameSignalStability = QFrame(self.infoGroupBox)
        self.boxFrameSignalStability.setObjectName(u"boxFrameSignalStability")
        sizePolicy3.setHeightForWidth(self.boxFrameSignalStability.sizePolicy().hasHeightForWidth())
        self.boxFrameSignalStability.setSizePolicy(sizePolicy3)
        self.boxFrameSignalStability.setMinimumSize(QSize(170, 20))
        self.boxFrameSignalStability.setMaximumSize(QSize(16777215, 35))
        self.boxFrameSignalStability.setFrameShape(QFrame.Shape.Box)
        self.boxFrameSignalStability.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.boxFrameSignalStability)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(10, 5, 10, 5)
        self.signalStabilityLabelInfo = QLabel(self.boxFrameSignalStability)
        self.signalStabilityLabelInfo.setObjectName(u"signalStabilityLabelInfo")
        sizePolicy3.setHeightForWidth(self.signalStabilityLabelInfo.sizePolicy().hasHeightForWidth())
        self.signalStabilityLabelInfo.setSizePolicy(sizePolicy3)
        font4 = QFont()
        font4.setPointSize(18)
        font4.setBold(True)
        font4.setKerning(True)
        self.signalStabilityLabelInfo.setFont(font4)
        self.signalStabilityLabelInfo.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_5.addWidget(self.signalStabilityLabelInfo)


        self.signalStabilityHLayout.addWidget(self.boxFrameSignalStability)


        self.horizontalLayout.addLayout(self.signalStabilityHLayout)

        self.info_frame_2 = QFrame(self.infoGroupBox)
        self.info_frame_2.setObjectName(u"info_frame_2")
        self.info_frame_2.setFrameShape(QFrame.Shape.VLine)
        self.info_frame_2.setFrameShadow(QFrame.Shadow.Raised)

        self.horizontalLayout.addWidget(self.info_frame_2)

        self.amplifiedDataHLayout = QHBoxLayout()
        self.amplifiedDataHLayout.setSpacing(0)
        self.amplifiedDataHLayout.setObjectName(u"amplifiedDataHLayout")
        self.amplifiedDataHLayout.setSizeConstraint(QLayout.SizeConstraint.SetMinimumSize)
        self.amplifiedDataLabel = QLabel(self.infoGroupBox)
        self.amplifiedDataLabel.setObjectName(u"amplifiedDataLabel")
        sizePolicy1.setHeightForWidth(self.amplifiedDataLabel.sizePolicy().hasHeightForWidth())
        self.amplifiedDataLabel.setSizePolicy(sizePolicy1)
        self.amplifiedDataLabel.setMinimumSize(QSize(130, 0))
        font5 = QFont()
        font5.setPointSize(18)
        font5.setWeight(QFont.Medium)
        font5.setItalic(False)
        font5.setUnderline(False)
        font5.setStrikeOut(False)
        self.amplifiedDataLabel.setFont(font5)
        self.amplifiedDataLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.amplifiedDataHLayout.addWidget(self.amplifiedDataLabel)

        self.amplifiedDataButton = QPushButton(self.infoGroupBox)
        self.amplifiedDataButton.setObjectName(u"amplifiedDataButton")
        sizePolicy2.setHeightForWidth(self.amplifiedDataButton.sizePolicy().hasHeightForWidth())
        self.amplifiedDataButton.setSizePolicy(sizePolicy2)
        self.amplifiedDataButton.setMinimumSize(QSize(80, 20))
        self.amplifiedDataButton.setMaximumSize(QSize(16777215, 35))
        font6 = QFont()
        font6.setPointSize(18)
        font6.setWeight(QFont.Medium)
        self.amplifiedDataButton.setFont(font6)
        self.amplifiedDataButton.setCheckable(True)
        self.amplifiedDataButton.setChecked(False)

        self.amplifiedDataHLayout.addWidget(self.amplifiedDataButton)


        self.horizontalLayout.addLayout(self.amplifiedDataHLayout)

        self.info_frame_3 = QFrame(self.infoGroupBox)
        self.info_frame_3.setObjectName(u"info_frame_3")
        self.info_frame_3.setFrameShape(QFrame.Shape.VLine)
        self.info_frame_3.setFrameShadow(QFrame.Shadow.Raised)

        self.horizontalLayout.addWidget(self.info_frame_3)

        self.connectivityCheckHLayout = QHBoxLayout()
        self.connectivityCheckHLayout.setSpacing(0)
        self.connectivityCheckHLayout.setObjectName(u"connectivityCheckHLayout")
        self.connectivityCheckHLayout.setSizeConstraint(QLayout.SizeConstraint.SetMinimumSize)
        self.connectivityCheckLabel = QLabel(self.infoGroupBox)
        self.connectivityCheckLabel.setObjectName(u"connectivityCheckLabel")
        sizePolicy1.setHeightForWidth(self.connectivityCheckLabel.sizePolicy().hasHeightForWidth())
        self.connectivityCheckLabel.setSizePolicy(sizePolicy1)
        self.connectivityCheckLabel.setMinimumSize(QSize(176, 0))
        font7 = QFont()
        font7.setPointSize(18)
        font7.setWeight(QFont.Medium)
        font7.setItalic(False)
        font7.setKerning(True)
        self.connectivityCheckLabel.setFont(font7)
        self.connectivityCheckLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.connectivityCheckHLayout.addWidget(self.connectivityCheckLabel)

        self.connectivityCheckButton = QPushButton(self.infoGroupBox)
        self.connectivityCheckButton.setObjectName(u"connectivityCheckButton")
        sizePolicy2.setHeightForWidth(self.connectivityCheckButton.sizePolicy().hasHeightForWidth())
        self.connectivityCheckButton.setSizePolicy(sizePolicy2)
        self.connectivityCheckButton.setMinimumSize(QSize(80, 20))
        self.connectivityCheckButton.setMaximumSize(QSize(16777215, 35))
        self.connectivityCheckButton.setFont(font6)
        self.connectivityCheckButton.setCheckable(True)
        self.connectivityCheckButton.setChecked(False)

        self.connectivityCheckHLayout.addWidget(self.connectivityCheckButton)


        self.horizontalLayout.addLayout(self.connectivityCheckHLayout)


        self.verticalLayout_4.addWidget(self.infoGroupBox, 0, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.verticalLayout_4.setStretch(0, 3)
        MainWindowVoltage.setCentralWidget(self.centralWidgetVoltage)
        self.menuBar = QMenuBar(MainWindowVoltage)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1280, 23))
        font8 = QFont()
        font8.setPointSize(12)
        font8.setBold(False)
        self.menuBar.setFont(font8)
        self.menuPlantLeaf = QMenu(self.menuBar)
        self.menuPlantLeaf.setObjectName(u"menuPlantLeaf")
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuExperiment = QMenu(self.menuBar)
        self.menuExperiment.setObjectName(u"menuExperiment")
        self.menuSettings = QMenu(self.menuBar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuChoose_Theme = QMenu(self.menuSettings)
        self.menuChoose_Theme.setObjectName(u"menuChoose_Theme")
        self.menuChoose_Font_Scale = QMenu(self.menuSettings)
        self.menuChoose_Font_Scale.setObjectName(u"menuChoose_Font_Scale")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindowVoltage.setMenuBar(self.menuBar)
        self.toolBar = QToolBar(MainWindowVoltage)
        self.toolBar.setObjectName(u"toolBar")
        sizePolicy3.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy3)
        font9 = QFont()
        font9.setPointSize(13)
        self.toolBar.setFont(font9)
        self.toolBar.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(Qt.ToolBarArea.TopToolBarArea)
        self.toolBar.setOrientation(Qt.Orientation.Horizontal)
        self.toolBar.setIconSize(QSize(32, 32))
        self.toolBar.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindowVoltage.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuExperiment.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuBar.addAction(self.menuPlantLeaf.menuAction())
        self.menuPlantLeaf.addAction(self.actionHome)
        self.menuPlantLeaf.addAction(self.actionQuit)
        self.menuPlantLeaf.addSeparator()
        self.menuPlantLeaf.addAction(self.actionInfo)
        self.menuPlantLeaf.addAction(self.actionVersion)
        self.menuPlantLeaf.addAction(self.actionWebSite)
        self.menuPlantLeaf.addAction(self.actionLicense)
        self.menuFile.addAction(self.actionNewFile)
        self.menuFile.addAction(self.actionOpenFile)
        self.menuFile.addAction(self.actionSave)
        self.menuExperiment.addAction(self.actionStart)
        self.menuExperiment.addAction(self.actionClear)
        self.menuExperiment.addAction(self.actionReplay)
        self.menuExperiment.addSeparator()
        self.menuExperiment.addAction(self.actionSerialPort)
        self.menuExperiment.addAction(self.actionSamplingSettings)
        self.menuSettings.addAction(self.menuChoose_Theme.menuAction())
        self.menuSettings.addAction(self.menuChoose_Font_Scale.menuAction())
        self.menuChoose_Theme.addAction(self.actionDark)
        self.menuChoose_Theme.addAction(self.actionDark_Green)
        self.menuChoose_Theme.addAction(self.actionDark_Blue)
        self.menuChoose_Theme.addAction(self.actionDark_Amber)
        self.menuChoose_Theme.addSeparator()
        self.menuChoose_Theme.addAction(self.actionLight)
        self.menuChoose_Theme.addAction(self.actionLight_Green)
        self.menuChoose_Theme.addAction(self.actionLight_Blue)
        self.menuChoose_Theme.addAction(self.actionLight_Amber)
        self.menuChoose_Font_Scale.addAction(self.actionVery_Small)
        self.menuChoose_Font_Scale.addAction(self.actionSmall)
        self.menuChoose_Font_Scale.addAction(self.actionMedium)
        self.menuChoose_Font_Scale.addAction(self.actionLarge)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionDocumentation)
        self.toolBar.addAction(self.actionHome)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNewFile)
        self.toolBar.addAction(self.actionOpenFile)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUpdatedTimeWindow)
        self.toolBar.addAction(self.actionClear)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSerialPort)
        self.toolBar.addAction(self.actionViewGrid)
        self.toolBar.addAction(self.actionSamplingSettings)

        self.retranslateUi(MainWindowVoltage)

        QMetaObject.connectSlotsByName(MainWindowVoltage)
    # setupUi

    def retranslateUi(self, MainWindowVoltage):
        MainWindowVoltage.setWindowTitle(QCoreApplication.translate("MainWindowVoltage", u"MainWindow", None))
        self.actionNewFile.setText(QCoreApplication.translate("MainWindowVoltage", u"New File", None))
#if QT_CONFIG(tooltip)
        self.actionNewFile.setToolTip(QCoreApplication.translate("MainWindowVoltage", u"New File", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionNewFile.setShortcut(QCoreApplication.translate("MainWindowVoltage", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpenFile.setText(QCoreApplication.translate("MainWindowVoltage", u"Open File", None))
#if QT_CONFIG(tooltip)
        self.actionOpenFile.setToolTip(QCoreApplication.translate("MainWindowVoltage", u"Open...", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionOpenFile.setShortcut(QCoreApplication.translate("MainWindowVoltage", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("MainWindowVoltage", u"Save As", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("MainWindowVoltage", u"Save As...", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindowVoltage", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionHome.setText(QCoreApplication.translate("MainWindowVoltage", u"Home", None))
#if QT_CONFIG(tooltip)
        self.actionHome.setToolTip(QCoreApplication.translate("MainWindowVoltage", u"Home", None))
#endif // QT_CONFIG(tooltip)
        self.actionSerialPort.setText(QCoreApplication.translate("MainWindowVoltage", u"Serial Port", None))
#if QT_CONFIG(tooltip)
        self.actionSerialPort.setToolTip(QCoreApplication.translate("MainWindowVoltage", u"Choose Serial Port", None))
#endif // QT_CONFIG(tooltip)
        self.actionViewGrid.setText(QCoreApplication.translate("MainWindowVoltage", u"View Grid", None))
#if QT_CONFIG(tooltip)
        self.actionViewGrid.setToolTip(QCoreApplication.translate("MainWindowVoltage", u"View Grid", None))
#endif // QT_CONFIG(tooltip)
        self.actionSamplingSettings.setText(QCoreApplication.translate("MainWindowVoltage", u"Sampling Settings", None))
#if QT_CONFIG(tooltip)
        self.actionSamplingSettings.setToolTip(QCoreApplication.translate("MainWindowVoltage", u"Sampling Settings", None))
#endif // QT_CONFIG(tooltip)
        self.actionInfo.setText(QCoreApplication.translate("MainWindowVoltage", u"Info", None))
        self.actionVersion.setText(QCoreApplication.translate("MainWindowVoltage", u"Version", None))
        self.actionWebSite.setText(QCoreApplication.translate("MainWindowVoltage", u"WebSite", None))
        self.actionLicense.setText(QCoreApplication.translate("MainWindowVoltage", u"License", None))
        self.actionStart.setText(QCoreApplication.translate("MainWindowVoltage", u"Start/Stop", None))
        self.actionClear.setText(QCoreApplication.translate("MainWindowVoltage", u"Clear", None))
        self.actionReplay.setText(QCoreApplication.translate("MainWindowVoltage", u"Replay", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindowVoltage", u"About...", None))
        self.actionDocumentation.setText(QCoreApplication.translate("MainWindowVoltage", u"Documentation", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindowVoltage", u"Quit", None))
        self.actionDark.setText(QCoreApplication.translate("MainWindowVoltage", u"Dark", None))
        self.actionDark_Green.setText(QCoreApplication.translate("MainWindowVoltage", u"Dark Green", None))
        self.actionDark_Blue.setText(QCoreApplication.translate("MainWindowVoltage", u"Dark Blue", None))
        self.actionDark_Amber.setText(QCoreApplication.translate("MainWindowVoltage", u"Dark Amber", None))
        self.actionLight.setText(QCoreApplication.translate("MainWindowVoltage", u"Light", None))
        self.actionLight_Green.setText(QCoreApplication.translate("MainWindowVoltage", u"Light Green", None))
        self.actionLight_Blue.setText(QCoreApplication.translate("MainWindowVoltage", u"Light Blue", None))
        self.actionLight_Amber.setText(QCoreApplication.translate("MainWindowVoltage", u"Light Amber", None))
        self.actionVery_Small.setText(QCoreApplication.translate("MainWindowVoltage", u"Very Small", None))
        self.actionSmall.setText(QCoreApplication.translate("MainWindowVoltage", u"Small", None))
        self.actionMedium.setText(QCoreApplication.translate("MainWindowVoltage", u"Medium", None))
        self.actionLarge.setText(QCoreApplication.translate("MainWindowVoltage", u"Large", None))
        self.actionUpdatedTimeWindow.setText(QCoreApplication.translate("MainWindowVoltage", u"updatedTimeWindow", None))
        self.infoGroupBox.setTitle("")
        self.startStopButton.setText(QCoreApplication.translate("MainWindowVoltage", u"START", None))
        self.signalStabilityLabelWritten.setText(QCoreApplication.translate("MainWindowVoltage", u"Signal Stability:", None))
        self.signalStabilityLabelInfo.setText(QCoreApplication.translate("MainWindowVoltage", u"NOT CONNECTED", None))
        self.amplifiedDataLabel.setText(QCoreApplication.translate("MainWindowVoltage", u"Amplified Data:  ", None))
        self.amplifiedDataButton.setText(QCoreApplication.translate("MainWindowVoltage", u"OFF", None))
        self.connectivityCheckLabel.setText(QCoreApplication.translate("MainWindowVoltage", u"Connectivity Check:", None))
        self.connectivityCheckButton.setText(QCoreApplication.translate("MainWindowVoltage", u"OFF", None))
        self.menuPlantLeaf.setTitle(QCoreApplication.translate("MainWindowVoltage", u"About", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindowVoltage", u"File", None))
        self.menuExperiment.setTitle(QCoreApplication.translate("MainWindowVoltage", u"Experiment", None))
        self.menuSettings.setTitle(QCoreApplication.translate("MainWindowVoltage", u"Settings", None))
        self.menuChoose_Theme.setTitle(QCoreApplication.translate("MainWindowVoltage", u"Choose Theme", None))
        self.menuChoose_Font_Scale.setTitle(QCoreApplication.translate("MainWindowVoltage", u"Choose Font Scale", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindowVoltage", u"Help", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindowVoltage", u"toolBar", None))
    # retranslateUi

